### ISSUE TITLE
Question: EC update

### ISSUE THREAD

**Issue by kratz00** [gch1p/thinkpad-bios-software-flashing-guide#1]
In case of a downgrade, would it also downgrade the EC version?

**Comment by gch1p** [comment]
I don't think so, because you explicitly ask dosflash to flash FL1 file, which is the BIOS image. EC update is stored in FL2 file, and dosflash shouldn't touch it or even know about its existence.

To flash EC, you would need to use another command:
```
dosflash.exe /sd /ipf ec /file <directory>\<file>.FL2
```

**Comment by kratz00** [comment]
Thanks, good to know.

Afaik the only way to upgrade the EC is using the offical Lenovo BIOS update.
Do you think it is worth adding some notes like:

1. to use the latest official Lenovo BIOS update to get the latest EC update before downgrading
2. that a downgrade will only affect the BIOS and not the EC

I would be willing the create a PR :)

Bonus question:
IIRC there are four regions IFD, GBE, ME and BIOS.
With your method it is only possible to update the BIOS region, right?
So if I wanted to use me_cleaner to deblob ME, I would still need an external flasher?

**Comment by gch1p** [comment]
> Afaik the only way to upgrade the EC is using the offical Lenovo BIOS update.

Or doing what [thinkpad-ec](https://github.com/hamishcoleman/thinkpad-ec) project does. They patch bootable CD in a similar way that I do, calling dosflash directly.

> Do you think it is worth adding some notes

I think yes, thank you.

> IIRC there are four regions IFD, GBE, ME and BIOS.

Correct.

> With your method it is only possible to update the BIOS region, right?

I guess GBE is writable too, but I'm not sure, don't have an X230 on hand right now to check.
The IFD and ME are still read-only (and ME is locked). Their permissions are defined in IFD itself, and there is no way that I know of to overwrite FD internally. Oh wait, I know one: asserting HDA_SDO high on startup will unlock FD until the next reboot. It's called "pinmod", but I guess it's a pain to use and even not safe. Easier to get an external flasher.

As to ME, there is HMRFPO command, that can be sent to ME during initialization stage (from the BIOS) before EOF (End-Of-Post) that is supposed to suspend it temporarily and unlock ME SPI region for writing on the next reboot. This is a way for vendors to update ME firmware. 

That would allow us to flash even me_cleaned ME image internally, without touching the chip. But I was testing it today (and yesterday) on my X230 and unfortunately it doesn't work: ME returns an error instead of accepting the command. One of coreboot developers who tried to do the same last year said that they had the same issue on some other ThinkPad. It appears it not always works. There's still a small chance that I made some mistake, but for now I believe I didn't (at least according to publicly known information about this HMRFPO command).

But there is good news: just an hour ago I successfully implemented a "Soft Temporary Disable" mode for ME in coreboot, and it works, at least on my X230. In this mode, the ME stays in a BUP phase. I plan to polish it and then submit a patch.

So, going back to your question,

>  if I wanted to use me_cleaner to deblob ME, I would still need an external flasher?

yes, if you want to overwrite an ME region on the chip with deblobbed image to be 100% sure that it's neutralized, you still need an external flasher, at least until the moment we find a way to execute HMRFPO successfully. But disabling ME with software methods should be possible soon, I hope.

**Comment by gch1p** [comment]
I think I will add all this info to the README later, seems useful.

**Comment by gch1p** [comment]
Software Disable Mode patch, by the way: https://review.coreboot.org/c/coreboot/+/37115

**Comment by n4ru** [comment]
Correct me if I'm wrong, but doesn't the heads project flash ONLY the 4MB chip (which is BIOS only), and then boots into a payload that allows flashing of the entire 12MB region? There is no flashing of the 8MB chip at all.

In theory, we should be able to implement a payload that we can software flash, boot into it, then flash the entire 12MB region from it.

Source: http://osresearch.net/Building

```Initial SPI2 (4MB) flash chips —– x230 and x220 boards needs their 4MB SPI2 to be initially externally flashed, while the 12MB rom needs to be flashed internally from within Heads to make sure to not screw up with ME, contained in the SPI1 flash (8MB bottom flash chip under keyboad)```

**Comment by gch1p** [comment]
I don't know much about Heads project, but that is wrong. You can overwrite write-protected FD and ME regions only externally (for the first time, at least). Their permissions are not controlled by SPI Protected Ranges registers (which are set by BIOS), but by IFD itself. There are two known exceptions for this rule.

1. If you assert HDA_SDO pin high (on older machines like X200, you need to assert GPIO33 low instead) and hold it while booting, FD access permissions will be temporary ignored and you will be able to flash FD. (Not sure about ME.) This is described in Intel's datasheets.

2. If you issue HMRFPO (which stands for Host ME Region Flash Protection Override) command to the ME (from BIOS) before POST, ME region will become writable after next reboot. Unfortunately I couldn't to reproduce it on X230.

I guess they just mean flashing whole BIOS region internally (with `--ifd - i bios` flashrom arguments or something similar) afterwards, which is larger than 4MB (part of it is on 8MB chip). But anyway, to be able to flash whole 12MB internally, first you need to flash 8MB chip externally (or successfully apply both HDA_SDO and HMRFPO hacks).

P.S. That page is also wrong about x220: x220 has only one SPI flash chip of 8MB.

P.P.S. Apple does not protects FD and ME on MacBooks (they even run ME in manufacture mode in production), at least on 2011-2013 models (didn't check other models), so on MacBooks it's possible to flash whole chip, i.e. flash coreboot, neuter ME and so on, completely internally (I even have a [script](https://github.com/gch1p/mmga) for that).

**Comment by n4ru** [comment]
So if I have that right, they just use part of the 8MB chip for the BIOS, and when flashing updates they are also simply flashing that same region? So flashing again within coreboot should be fine as long as it still remains within the BIOS region.

P.S. If you are not already in the r/ThinkPad discord we would love to have you - http://discord.gg/Ybdz7AS

There are a lot of TP projects floating around including new hardware mods and software that the community works on behind closed doors in there.

**Comment by gch1p** [comment]
> So if I have that right, they just use part of the 8MB chip for the BIOS, and when flashing updates they are also simply flashing that same region? So flashing again within coreboot should be fine as long as it still remains within the BIOS region.

Well, I think yes. I don't see how they can flash anything besides `bios` **IF they don't unlock the flash descriptor**.

They have [this page](https://github.com/osresearch/heads-wiki/blob/master/Clean-the-ME-firmware.md) about neutering ME where they use external programmer to dump ME in the example.

And in the [page you linked](http://osresearch.net/Building), here's what they're saying:
> while the 12MB rom needs to be flashed internally from within Heads **to make sure to not screw up with ME**

I think this means they don't touch ME when flashing internally, to "not screw up" with it.

> So flashing again within coreboot should be fine as long as it still remains within the BIOS region.

Of course.
