### ISSUE TITLE
Much easier way to downgrade, no El Torito acrobatics needed

### ISSUE THREAD

**Issue by myself248** [gch1p/thinkpad-bios-software-flashing-guide#15]
To bypass autoexec.bat, just spam F5 during DOS boot. 

So:
1. Download the BIOS update .ISO from Lenovo
2. Write it to bootable media (in my case, I'm just loading it on an iodd)
3. Boot from it using F12 to pick a temporary start device
4. Immediately after hitting enter to select the boot device, mash the f5 key
5. You should see "Starting PC-DOS...." and then immediately get a command prompt
6. cd flash
7. dir /s
8. dosflash /sd /file g4eta0ww\\$01d5100.fl1 

30-year-stale DOS super-powers, activate!

**Comment by bengalih** [comment]
The whole documented process seems overly convoluted, or at the very least out of date.
For those of you who can boot into Windows, the easiest way to downgrade the BIOS is simply:
https://github.com/n4ru/IVprep

Running the above to downgrade and then creating the live USB from:
https://github.com/n4ru/1vyrain

Is the simplest and easiest method.  I spent about an hour looking through the various instructions which are full of good technical information, but seemingly disjointed due to not being kept updated/synced for several years.

The downgrade and update to modded BIOS on my W530 took less than 10 minutes following this procedure.
And while you should know what you are getting into, the maximum level of technical expertise needed to do this amounts to knowing how to make a bootable ISO.

**Comment by gch1p** [comment]
@bengalih 
ivprep/1vyrain is **based** on my research described in this article as well as the research of those who is referenced in the "credits" section.

**Comment by bengalih** [comment]
> @bengalih ivprep/1vyrain is **based** on my research described in this article as well as the research of those who is referenced in the "credits" section.

I have no reason to dispute your claims or to take any credit away from them (and therefore, thanks by the way).
I am simply stating to others who happened upon this as  I did (as I like to look at open issues before I begin implementing a project) that there is a much easier way to do this mid-2023.

I don't know if there is/was a pissing contest or bad blood between the different projects or simply a lack of upkeep between keeping the projects aware of each other.  The latter can't be blamed since this is clearly an older project meant for machines that don't get as much use anymore.  That being said, the fact this issue was still open after 17 months just speaks to my point.

Anyway, again - thanks for your work on this project, I just wanted the average-Joe to know that this whole process is now simplified thanks to the developed works of you and other devs.

Now that I'm modded, I'm off in search of some good  documentation as to how to actually make use of it...
